### ISSUE TITLE
Cannot find matching method package.TaskSearchService#readOnly(boolean). Please check if the declared type is right and if the method exists.

### ISSUE THREAD

**Issue by rcalastro** [MayGo/grails-scaffold-angular#8]
I'm following the steps to install and run the plugin, but occurs an error when I run "create-demo" command for the second time and the following ones as well. 

>  Error Compilation error: startup failed:
> /Users/XXXXX/Dev/Ang/grails-app/services/ang/TaskSearchService.groovy: 49: [Static type checking] - Cannot find matching method ang.TaskSearchService#readOnly(boolean). Please check if the declared type is right and if the method exists.
>  @ line 49, column 4.
>             readOnly(doReadOnly)
>       ^

I tried to comment the 49 line in TaskSeachService and after that I was able to run the second "create-demo", comment line again and then run-app.

```
    PagedResultList search(OcorrenciaSearchCommand cmd, Map pagingParams, boolean doReadOnly = true) {

        BuildableCriteria criteriaBuilder = (BuildableCriteria) Ocorrencia.createCriteria()
        PagedResultList results = (PagedResultList) criteriaBuilder.list(
                offset: pagingParams.offset,
                max: pagingParams.max,
                order: pagingParams.order,
                sort: pagingParams.sort
        ) {
            searchCriteria criteriaBuilder, cmd
            // readOnly(doReadOnly)
        }

        return results
    }
```

Now, running app, there is another issue that i cant "solve", the list page alway returns server error 500.
Create and edit works fine. Dashboard list also works, but when i click in Task page, nothing is listed and a message says 

> Network error (500): Internal Server Error for url:http://localhost:8080/Ang/ocorrencias/v1

and here is the console log:
sort: id

> ```
>   max: 15
>   order: asc
>   offset: 0
>   Cannot cast object 'grails.orm.PagedResultList@2c5a7a7b' with class 'grails.orm.PagedResultList' to class 'grails.gorm.PagedResultList' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: grails.gorm.PagedResultList(ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task). Stacktrace follows:
>   Message: Cannot cast object 'grails.orm.PagedResultList@2c5a7a7b' with class 'grails.orm.PagedResultList' to class 'grails.gorm.PagedResultList' due to: groovy.lang.GroovyRuntimeException: Could not find matching constructor for: grails.gorm.PagedResultList(ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task, ang.Task)
>       Line | Method
>   ->>   42 | $tt__search            in ang.TaskSearchService
>   - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
>   |     37 | traceServiceMethodCall in defpackage.aop.ServicesLogging
>   |     47 | index . . . . . . . .  in ang.v1.TaskController
>   |    177 | doFilter               in grails.plugin.cache.web.filter.PageFragmentCachingFilter
>   |     63 | doFilter . . . . . . . in grails.plugin.cache.web.filter.AbstractFilter
>   |     82 | doFilter               in com.brandseye.cors.CorsFilter
>   |   1145 | runWorker . . . . . .  in java.util.concurrent.ThreadPoolExecutor
>   |    615 | run                    in java.util.concurrent.ThreadPoolExecutor$Worker
>   ^    722 | run . . . . . . . . .  in java.lang.Thread
> ```

Could anybody help-me how to solve or any useful tip? I think it is connected with readOnly(boolean) error.

My Grails version is 2.4.3 as suggest
My Task domain class is very simple, with just two String attributes: responsible and description. If the project run ok, I'm planning to add more attributes and domains. For now I just want to run the application with the 'dynamic angular scaffolding'.

Thanks

**Comment by MayGo** [comment]
Remove annotation @GrailsCompileStaticfrom *SearchService and try again.

**Comment by rcalastro** [comment]
I tried to remove annotation as you suggest, but the same error persists:

> Cannot cast object 'grails.orm.PagedResultList@28d4899d' with class 'grails.orm.PagedResultList' to class 'grails.gorm.PagedResultList' due to: groovy.lang.GroovyRuntimeException (...)

It looks like a bug of Grails 2.4.3 version. 

I found this [https://jira.grails.org/browse/GRAILS-8413](url)

**Comment by MayGo** [comment]
I suggest to upgrade to grails 2.4.5 and see if that fixes it.

2016-03-20 21:42 GMT+02:00 Rafael notifications@github.com:
